version: '3.1'

services:

  ghost:
    image: ghost:latest
    restart: always
    ports:
      - 8081:2368
    volumes:
          - Ghost_storage:/var/lib/ghost/content
    depends_on:
            - Mysql 
  Mysql:
      image: mysql:5.7
      environment:
                MYSQL_ROOT_PASSWORD: hritick524
                MYSQL_DATABASE: Ghostdb
                MYSQL_USER: Hritick
                MYSQL_PASSWORD: hritick524
                MYSQL_DATABASE: mydatabase

      restart: always
      volumes:
            - mysql_storage2:/var/lib/mqsql
volumes:
      mysql_storage2:
      Ghost_storage:
