version: '3.1'
services:
    joomlacms:
            image: joomla
            volumes:
                 - myjoomla_storage:/var/www/html/
                          
            restart: always
            ports:
            - 4444:80
            depends_on:
                   - mysqldbs
            environment:
                   JOOMLA_DB_USER: hritick
                   JOOMLA_DB_PASSWORD: hritick524
                   JOOMLA_DB_HOST: mysqldbs
                   JOOMLA_DB_NAME: joomladb

    mysqldbs:
            image: mysql:5.7
            volumes:
                 - mysql_storage:/var/lib/mysql
            restart: always
            environment:
                     MYSQL_ROOT_PASSWORD: Hritick524
                     MYSQL_USER: hritick
                     MYSQL_PASSWORD: hritick524
                     MYSQL_DATABASE: joomladb
volumes:
      mysql_storage:
      myjoomla_storage:
        
      

